@echo off


CALL LOG_ENTER pENV

call sENV
call pENV_MOD

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%SWAG_GEN_CONT%"
SET "PROJ_CONT_DATA_DIR=%SWAG_GEN_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%SWAG_GEN_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%SWAG_GEN_CONT_HOME_DIR%"
SET "PROJ_HOST=%SWAG_GEN_HOST%"
SET "PROJ_IMG=%SWAG_GEN_IMG%"
SET "PROJ_PORT_INT=%SWAG_GEN_PORT_INT%"


CALL LOG_EXIT pENV

