@echo off


CALL LOG_ENTER pENV

CALL sENV

SET "PROJ_LABEL=%SYS%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%SOAP_CONT%"
SET "PROJ_CONT_DATA_DIR=%SOAP_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%SOAP_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%SOAP_CONT_HOME_DIR%"
SET "PROJ_HOST=%SOAP_HOST%"
SET "PROJ_HOST_DIR=%SOAP_HOST_DIR%"
SET "PROJ_IMG=%SOAP_IMG%"
SET "PROJ_PASSWORD=%SOAP_PASSWORD%"
SET "PROJ_PORT_EXT=%SOAP_PORT_EXT%"
SET "PROJ_PORT_INT=%SOAP_PORT_INT%"
SET "PROJ_USER=%SOAP_USER%"
SET "PROJ_VOL=%SOAP_VOL%"
SET "PROJ_VOL_DIR=%SOAP_VOL_DIR%"

CALL LOG_EXIT pENV

