@echo off


CALL LOG_ENTER pENV

call sENV
call project\pENV_MOD

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%SOAP_CONT%"
SET "PROJ_CONT_DIR=%SOAP_CONT_DIR%"
SET "PROJ_CONT_MNT_DIR=%SOAP_CONT_MNT_DIR%"
SET "PROJ_HOST_DIR=%SOAP_HOST_DIR%"
SET "PROJ_HOST_MNT_DIR=%SOAP_HOST_MNT_DIR%"
SET "PROJ_IMG=%SOAP_IMG%"
SET "PROJ_PORT_INT=%SOAP_PORT_INT%"


CALL LOG_EXIT pENV

