FROM maven:3.6.3-jdk-11

USER root

ARG CONT_DIR
ARG HOST_DIR
ARG SYS_DIR

RUN echo CONT_DIR is ${CONT_DIR}
RUN echo HOST_DIR is ${HOST_DIR}
RUN echo SYS_DIR is ${SYS_DIR}

RUN mkdir -p ${CONT_DIR}
WORKDIR ${CONT_DIR}

COPY code .
COPY --chown=maven:maven .${HOST_DIR} ${CONT_DIR}
COPY ${SYS_DIR}/maven/settings.xml /home/maven/.m2

RUN mkdir src/main/resources/wsdl
COPY project/conf/service.wsdl ./src/main/resources/wsdl/service.wsdl


ENTRYPOINT ["mvn", "clean", "package"]
