FROM maven:3.6.3-jdk-11

USER root

ARG FILE_NAME
ARG CONT_DIR
ARG HOST_DIR


COPY ./code/pom.xml ./pom.xml

RUN mvn dependency:go-offline -B

COPY ./code/src ./src

RUN mkdir ./src/main/resources/wsdl

RUN echo FILE_NAME is $FILE_NAME

COPY ./system/soap/$FILE_NAME ./src/main/resources/wsdl

RUN MVN clean install

ENTRYPOINT [ "/bin/sh" ]

