FROM maven:3.6.3-jdk-8

USER root

ARG CONT_DIR
ARG HOST_DIR
ARG SYS_DIR
ARG TMPL_DIR

RUN echo CONT_DIR is ${CONT_DIR}
RUN echo HOST_DIR is ${HOST_DIR}
RUN echo SYS_DIR is ${SYS_DIR}
RUN echo TMPL_DIR is ${TMPL_DIR}

RUN mkdir -p ${CONT_DIR}

WORKDIR ${CONT_DIR}

COPY ./${TMPL_DIR}/mvn/pom.xml .
COPY ./${SYS_DIR}/soap/*.wsdl .

RUN mkdir -p /root/.m2
COPY ./${SYS_DIR}/maven/settings.public.xml /root/.m2/settings.xml

ENV ART $ART
ENV FILE $FILE
ENV GRP $GRP
ENV PKG $PKG
ENV REPO_URL $REPO_URL
ENV REPO_PORT $REPO_PORT
ENV VER $VER

ENTRYPOINT ["mvn", "deploy"]

#ENTRYPOINT ["/bin/sh"]
