FROM maven:3.6.3-jdk-11

USER root

ARG CONT_DIR
ARG FILE_NAME
ARG HOST_DIR

RUN mkdir $CONT_DIR
WORKDIR $CONT_DIR

RUN mkdir $HOME/.m2
COPY ./system/mvn/settings.xml $HOME/.m2

COPY ./code/pom.xml ./pom.xml

RUN mvn dependency:go-offline -B

COPY ./code/src ./src

RUN mkdir ./src/main/resources/wsdl

RUN echo FILE_NAME is $FILE_NAME

COPY ./system/soap/$FILE_NAME ./src/main/resources/wsdl


RUN mvn clean deploy

ENTRYPOINT [ "/bin/sh" ]

